### PR TITLE
Implemented fit to scene function for the tornado viewer

### PR DESCRIPTION
**Pull request by rainman110**
This function allows to fit the 3D scene into the viewer by
- computing the bounding sphere of the whole scene
- changing the camera position + near/far planes
- chaning the center of the orbiter.

The near/far planes settings prevent culling when zooming. Culling happened with the old implementation, as the near/far planes were set statically.

### CODE REVIEW

**Comment by rainman110** [comment]
@aothms It is probably best, if you could review the code. Please try shapes with differing sizes (order of magnitudes).

**Comment by jf---** [comment]
hi @rainman110 , 

Could you please rebase this PR on the current master?
There's a conflict...
Many thanks in advance...

**Comment by rainman110** [comment]
hi @jf---,
I did the rebase, you can merge if you want.

**Comment by jf---** [comment]
perfect, thanks @rainman110 !

**Pull request merged**
