### PR TITLE
Added a simple ifc file viewer

### PR DESCRIPTION
**Pull request by tpaviot**
This PR is a pythonocc based IFC file viewer. It relies on excellet @aothms IfcOpenShell.

Since this script relies in the pythonocc-contrib, it can be extended with other features. Please @jf--- feel free to improve this file or add a todo directly inside the script. Building industry is not my business, I'm not sure I would contribute useful features by myself.

### CODE REVIEW

**Comment by jf---** [comment]
@tpaviot , I think this is a very cool contribution, I'm :+1: for merging this now, and to have it to continue to evolve. Great work!

**Comment by tpaviot** [comment]
ok, perfect.

**Comment by aothms** [comment]
This is nice indeed. Thank you for using my library.

One of the things that makes IFC different from, say, STEP, is the extensive use of property sets to transfer metadata, e.g: https://github.com/tpaviot/pythonocc-contrib/commit/1bb5fd71d02feead5631d65946539fae525100e6#diff-d8e94da7ba395ad9210a014bcc0a16d5R84

@jf-- once promised me some sample to embed the PythonOCC viewer into more of an actual full-featured application window, with other interactive controls.

Is it also interesting for PythonOCC to have a sample of such interactivity? Maybe there already is? For example, upon selecting a TopoDS_Shape, the corresponding property set metadata for this instance from the IFC file is displayed.

I would happily contribute the code to nicely format and list the metadata from the file. But I'm a bit lost in finding an idiomatic python windowing framework and such a bi-directional selection mechanism.

Can we work on this together? Maybe this is something you could pull out of your hats with relative ease?

**Comment by tpaviot** [comment]
@aothms pythonocc already implements a selection mechanism, but it has actually been poorly used so far. This IFC viewer, based upon pythonocc, could be the opportunity to go beyond the SimpleGui and build a reals user interface (note that this UI must stay as simple as possible, since GUI programming can become a nightmare).

What we could do together:
- a Qt4 GUI that implements a simple menu (File->Open) ;
- a selection mechanism : select a shape, and for instance, change its color and hide/show the shape by hittinh s/h keys ;
- a right click on the shape shows its properties (from the PropertySet) ;
- filter shapes by types (IfcWalls, IfcDoors etc) from a set of checkboxes for instance.

I would be ok to contribute to such a project.

**Comment by jf---** [comment]
So, I've delved a lot deeper in Qt / GUI programming lately...

### A few ideas:
- a decent Topology tree would be welcome
  - something along the lines of [cad exchanger](http://cadexchanger.com/products.html#EOU)?
  - 
  - the ability to filter topology types ( only show solids or shells )
  - show bounding boxes
  - filter the tree on properties
  - be able to hide / show elements in the three 
  - the ability to graphically set the topology selection level ( say vertices + faces, but not edges ) 
  - query its basic properties ( area, volume, radius, curvature, point etc )
  - sync selection ( highlight in the tree what is selected in the viewer and visa versa )

What is mentioned above should be implemented generically, such that its of use regardless of the file format of the imported CAD data. I think it will be easy to agree on some of the functionality, I like all @tpaviot suggestions 

---

### missing abstractions

The key thing here is the **Model**
Once you have a decent model of the Cad tree and its properties, that is accesible in Qt putting together a UI isn't super hard. 

Finally, an abstraction that we're really lacking I feel is that of a **Scene**.
Rendering custom entities, handling selection, transformations, it all works pretty well in AIS, but its hard to put together. So a decent [scenegraph](https://github.com/Ultimaker/Uranium/tree/master/UM/Scene) would be a huge win if you ask me...

these 2 issues ( Model + Scene ) are much conflated...

---

### Qt5 vs Qt4

Forgive me to raise the ever surfacing matter of dependencies:
- moving from Qt4 -> Qt5 is more urgent than is generally perceived:
  - [Qt4 is no longer supported](http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/). This ended december 2015. 
  - Qt5 will see its [long term release](https://blog.qt.io/blog/2015/12/18/introducing-long-term-support/) in february. This release is possible as significant as Qt 4.8, and will be supported for three years.
- that is to say, I'm not in favour of using the old school Qt 4.8
  - I've learned the hard way, since I've worked a lot with traitsui / enaml ( wasted youth... )
  - QML is an absolutely blessing is you ask me... 
    - its declarative ( QML / Qt5 ) vs procedural ( widgets / Qt4 ) . I found that the declarative style helps a lot to think of clean API. The QML code is very succinct in comparison to the widget code, especially when doing anything "fun" ( think OpenGL / HUD )
  - Something like [Ultimaker's Uranium](https://github.com/Ultimaker/Uranium/tree/master/UM) is a pretty neat framework to build on top of / might serve as a meaningful reference for a clean architecture on modern Qt technology 

The reason for this admittedly somewhat entrenched reply is that making a GUI that is beautiful is a lot harder on Qt4, Qt5 / QML is a lot more fun to work on ( especially QML ) and that things like HUD gui's just are vastly easier to do in Qt5. The grass is a lot greener on the other side ;)

**Comment by aothms** [comment]
Thanks for picking this up.

One small thing I would like to add to @jf---'s list of visualisation features is the "insertion point" or "local coordinate system origin" or however you'd like to call it. Unfortunately I have no knowledge on Qt4/5 or QML to weigh in on that discussion.

I agree that a model and graph would be welcome abstractions. How does OCAF weigh in into this? I'm not familiar with it. With this level of ambition, is it feasible to take another step back and implement something in C++ and properly wrap it in Python to have a wider audience?

Obviously features should be implemented as generically as possible, but a possible way to approach this is to work from bottom to top. See what works well and then start to generalize things into higher order modules. @tpaviot's initial four features could be such a starting point. I would happily contribute, especially the things pertaining to IFC.

**Comment by tpaviot** [comment]
@jf--- Many things in your comment, too much things IMO. I suggest a pragmatic way, and a "simple viewer" target.

@aothms Of course everything is possible, including programming something in C++ and wrap it using python after. But it's not my intent with pythonocc. I'd like something 100% pure python, I don't want any compilation stage required in order to run the program on another machine/os.

The next step after this first ifc viwer draft is:
1. whenever a right click on a shape, display the list of related properties in the console
2. a file/open menu.

@aothms can you provide with a function that builds a dictionnary of all ifc entites with their related properties ?

@tpaviot: I take care of 2. and the event connected to 1. in order to call the function. This is just a couple of hours of work.

@jf--- You've beel talking about the power of Qt5 and QML for a few weeks. Can you please contribute a simple example (helloworld_qt5.py let's say, display a box in a Qt5 GUI using QML).

**Comment by jf---** [comment]
> "insertion point" or "local coordinate system origin" 

The "challenging" bit here is handling the transform in OCC.
The AIS_Trihedron can be used to interactively perform the transformation.
I've done the wiring on selecting such a gizmo / receiving signals from when such an entity is selected.

> How does OCAF weigh in into this? I'm not familiar with it. 

OCAF provides a lot of important mechanism.
However, I'm :+1: for re-doing what OCAF offers.
Too tiring to delve into it, but I might be wrong...

> With this level of ambition, is it feasible to take another step back and implement something in C++ and properly wrap it in Python to have a wider audience?

Possible, **but**:
- why? the performance isnt gonna be a deal breaker I expect...
- SO much more fun to do this work in python
- if something meaningful can be generalized, that will happen in the last stages of this effort...

> Obviously features should be implemented as generically as possible

We're missing meaningful signals to handle events from for instance...
For selection, its nice when something is selected and you just receive the TopoDS_Shape in your slot

> See what works well and then start to generalize things into higher order modules

Sounds like a plan.
I think a good start is to wrap the OCCUtils.Topo class in a Tree 

> @tpaviot's initial four features could be such a starting point. I would happily contribute, especially the things pertaining to IFC.

Agreed...
Cool, lets give the viewer some love ;)

lets see if a list can be formulated:
- [ ] Explore topology in tree widget
  - [ ] wrap the topology to a Qt AbstractItemModel
- [ ] Bind meaningful events ( think selection ) to signals
- [ ] think about a scenegraph

**Comment by jf---** [comment]
@tpaviot , yes, I've been working on this topic quite a bit...

the issue of  selection is already something I've addressed... ( through signal / slots )
I'll do a PR for that later today...

**Comment by tpaviot** [comment]
@jf--- I also have something to share related to selection, curious to see your solution

**Comment by aothms** [comment]
Just committed something. Hope it works for you. Not able to test on Python 3, but nothing serious should pop up there.

The committed class behaves like a dictionary but lazily loads it contents. As the amount of this metadata can be substantial. It can be converted to a vanilla python dict if that's what you need.

Just a quick note. This "simple_viewer" can quickly get quite equipotent to industry standard tools, especially considering it brings users the power of python(OCC) at their fingertips to manipulate, query and check their models. I'm really enthusiastic about this.

**Pull request merged**
